dist: bionic
language: python
python: 
      - '3.8.5'
      
before_script:
      - pip install -r requirements.txt

branches:
    only:
        - master 

env: DJANGO_SETTINGS_MODULE="projet_8.settings.travis"

services: 
      - postgresql

script:
      - ./manage.py test

