language: python
python:
      - '3.8.5'

addons:
        chrome: "stable"


before_script:
      - pip install -r requirements.txt
         # google chrome standalone driver
      - wget http://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - sudo mv chromedriver /usr/local/bin
      - sudo chmod a+x /usr/local/bin/chromedriver

branches:
  only:
      - master 

env:        
      - DJANGO_SETTINGS_MODULE="projet_8.settings.travis"

services: 
      - postgresql

script:
      - ./manage.py test

