# Generated by Django 3.1.7 on 2021-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(to="accounts.Favorite"),
        ),
    ]
