# Generated by Django 3.1.7 on 2021-04-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20210412_1310"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favorites",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
