# Generated by Django 3.1.7 on 2021-04-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=200)),
                ("stores", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                ("image", models.TextField(default=None)),
                ("nutriscore", models.IntegerField()),
                ("categories", models.ManyToManyField(to="products.Category")),
            ],
        ),
    ]
