# Generated by Django 3.1.7 on 2021-04-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products", to="products.Category"
            ),
        ),
    ]
