# Generated by Django 3.1.7 on 2021-04-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_favorite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
