# Generated by Django 3.1.7 on 2021-04-12 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0005_product_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="favorite",
            field=models.ManyToManyField(
                related_name="favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
