# Generated by Django 3.1.7 on 2021-04-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_auto_20210412_1945"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="favorite",
            new_name="favorites",
        ),
    ]
